//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace biz.dfch.PS.Abiquo.Client {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("biz.dfch.PS.Abiquo.Client.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: {1}.
        /// </summary>
        public static string ContractFailedEventHandler {
            get {
                return ResourceManager.GetString("ContractFailedEventHandler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid ParameterSetName &apos;{0}&apos; detected..
        /// </summary>
        public static string EnterServerInvalidParameterSetName {
            get {
                return ResourceManager.GetString("EnterServerInvalidParameterSetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login to &apos;{0}&apos; FAILED..
        /// </summary>
        public static string EnterServerLoginFailed1 {
            get {
                return ResourceManager.GetString("EnterServerLoginFailed1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login to &apos;{0}&apos; FAILED with tenant id {1} at second attempt..
        /// </summary>
        public static string EnterServerLoginFailed2 {
            get {
                return ResourceManager.GetString("EnterServerLoginFailed2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login to &apos;{0}&apos; FAILED with StatusCode {1} and message &apos;{1}&apos;..
        /// </summary>
        public static string EnterServerLoginWebException {
            get {
                return ResourceManager.GetString("EnterServerLoginWebException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uri &apos;{0}&apos; and ParameterSetName &apos;{1}&apos;..
        /// </summary>
        public static string EnterServerShouldProcess {
            get {
                return ResourceManager.GetString("EnterServerShouldProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Creating ConfigurationFileMap FAILED..
        /// </summary>
        public static string ImportConfigurationConfigurationFileMapCreateFailed {
            get {
                return ResourceManager.GetString("ImportConfigurationConfigurationFileMapCreateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Opening Configuration FAILED due to no file..
        /// </summary>
        public static string ImportConfigurationConfigurationHasFile {
            get {
                return ResourceManager.GetString("ImportConfigurationConfigurationHasFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Opening Configuration FAILED..
        /// </summary>
        public static string ImportConfigurationConfigurationOpenFailed {
            get {
                return ResourceManager.GetString("ImportConfigurationConfigurationOpenFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: The configuration file specified by the Path parameter must be a file and not a directory..
        /// </summary>
        public static string ImportConfigurationDirectoryExists {
            get {
                return ResourceManager.GetString("ImportConfigurationDirectoryExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: The configuration file specified by the Path parameter does not exist..
        /// </summary>
        public static string ImportConfigurationFileDoesNotExist {
            get {
                return ResourceManager.GetString("ImportConfigurationFileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving moduleContext to module variable FAILED..
        /// </summary>
        public static string ImportConfigurationSaveToModuleVariableFailed {
            get {
                return ResourceManager.GetString("ImportConfigurationSaveToModuleVariableFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Opening ConfigurationSection &apos;{1}&apos; FAILED..
        /// </summary>
        public static string ImportConfigurationSectionOpenFailed {
            get {
                return ResourceManager.GetString("ImportConfigurationSectionOpenFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import configuration from &apos;{0}&apos;.
        /// </summary>
        public static string ImportConfigurationShouldProcess {
            get {
                return ResourceManager.GetString("ImportConfigurationShouldProcess", resourceCulture);
            }
        }
    }
}
